### ISSUE TITLE
Website does not work

### ISSUE THREAD

**Issue by stevenbeeckman** [deepjs/deepjs#1]
https://www.deepjs.org/ does not work as it should. Please update the description of the repository.

**Comment by nomocas** [comment]
Planed in the next 3 weeks...;)

2014-04-25 1:17 GMT+02:00 Steven Beeckman notifications@github.com:

**Comment by toonketels** [comment]
https://www.deepjs.org links to https://ssl0.ovh.net/fr/.

**Comment by stevenbeeckman** [comment]
Correct. De GitHub http://github.compleet/deepjs zou wel moeten werken.
Op 4-sep.-2014 09:03 schreef "Toon Ketels" notifications@github.com:

**Comment by nomocas** [comment]
http://deepjs.github.io

closed.
